# Generated by Django 4.1.13 on 2024-03-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$390000$bfk2CY0GUBYUeTMoSDPX3Z$mdYOvu3D1dBK8Xm6xsHG0kS2ppiwakeGW0JnjD76tZ0=', max_length=128),
        ),
    ]
