# Generated by Django 4.1.13 on 2024-03-28 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_formdata_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formdata',
            name='password',
        ),
    ]
